watchingparty/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.auth.views import LogoutView


app_name = 'watchingparty'

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', LogoutView.as_view(), {'next_page': settings.LOGOUT_REDIRECT_URL},
    name='logout'),
    path('profile/', views.profileDetail, name='profile'),
    path('edit/', views.settingsDetail, name='settings'),
    path('edit/save/', views.profileSettings, name='save'),
    path('planMovie/', views.planMovie, name='planMovie'),
     path('<movietitle>/<description>/', views.movieInfo, name='movieInfo'),
    path('delete/<movietitle>/<description>/', views.deleteEvent, name='deleteEvent'),
    path('search/', views.SearchView.as_view(), name='search'),
    path('results/', views.SearchResultsView.as_view(), name='searchResults'),

]

watchparty/urls.py
from django.contrib import admin
from django.urls import include, path
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('watchingparty.urls')),
    path('accounts/', include('allauth.urls')),
]

watchingparty/models.py
from django.db import models


class Profile(models.Model):
    interests = models.TextField(
        default="This is a default interest. Please edit this in the profile settings if you want"
                " people to see your interests.")
    userName = models.CharField(max_length=200, default="")
    firstFavoriteMovie = models.CharField(max_length=200, default="")
    secondFavoriteMovie = models.CharField(max_length=200, default="")
    thirdFavoriteMovie = models.CharField(max_length=200, default="")
    fourthFavoriteMovie = models.CharField(max_length=200, default="")
    fifthFavoriteMovie = models.CharField(max_length=200, default="")
    firstFavoriteTVShow = models.CharField(max_length=200, default="")
    secondFavoriteTVShow = models.CharField(max_length=200, default="")
    thirdFavoriteTVShow = models.CharField(max_length=200, default="")
    fourthFavoriteTVShow = models.CharField(max_length=200, default="")
    fifthFavoriteTVShow = models.CharField(max_length=200, default="")
    reviews = models.TextField(default="This is a default review.")

    def __str__(self):
        return self.firstFavoriteMovie


class Meeting(models.Model):
    link = models.CharField(max_length=200)
    password = models.CharField(max_length=200)
    username = models.CharField(max_length=20, default="")
    movieTitle = models.CharField(max_length=200, default="")


class Event(models.Model):
    DEFAULT_PROFILE_ID = 1
    mediaTitle = models.CharField(max_length=200)
    username = models.CharField(max_length=20)
    # if the creator of an event deletes their account, don't delete the event
    creator = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='creator_profile',
                                default=DEFAULT_PROFILE_ID)
    eventDate = models.DateTimeField('date published')
    platform = models.CharField(max_length=200)  # for image files
    address = models.CharField(max_length=200, default="375 Merchant Walk Sq")
    city = models.CharField(max_length=200, default="Charlottesville")
    # has attributes year, month, day, hour, minute, second, tzinfo
    description = models.CharField(max_length=200)
    # an event can have multiple participants
    participant = models.ManyToManyField(Profile)

    def __str__(self):
        return self.mediaTitle + " with " + self.username

watchingparty/forms.py
from django import forms

from watchingparty import models


class ProfileForms(forms.Form):
    class Meta:
        model = models.Profile;

watchingparty/views.py
"""
REFERENCES

Title: <Openrouteservice Directions Service (GET)>
Author: <Openrouteservice>
URL: <https://openrouteservice.org/dev/#/api-docs/v2/directions/{profile}/get>

Title: <How to create a meeting with zoom API in Python?>
Date: <January 19th, 2022>
Code version: <Python 3>
URL: <https://www.geeksforgeeks.org/how-to-create-a-meeting-with-zoom-api-in-python/>

"""

from django.template import loader
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.contrib import messages
from .forms import ProfileForms
import requests
import json
import geocoder
import jwt
from time import time
from .models import Event, Profile, Meeting
from django.views.generic import TemplateView, ListView
from django.db.models import Q

def index(request):
    card_set = Event.objects.all()
    temp = loader.get_template('index.html')
    context = {
        'events': card_set,
    }
    if request.user.is_authenticated:
        if(Profile.objects.filter(userName=request.user).last() == None):
            currentUser = Profile(interests="", userName=request.user, firstFavoriteMovie="",
                            secondFavoriteMovie="", thirdFavoriteMovie="", fourthFavoriteMovie="",
                            fifthFavoriteMovie="", firstFavoriteTVShow="", secondFavoriteTVShow="", 
                            thirdFavoriteTVShow="", fourthFavoriteTVShow="", fifthFavoriteTVShow="")
            currentUser.save()
    return render(request, 'index.html', context)


def deleteEvent(request, movietitle, description):
    profile = Profile.objects.filter(userName=request.user).last()
    events = Event.objects.filter(participant=profile)
    event = Event.objects.filter(mediaTitle__exact=movietitle, description__exact=description).last()
    event.participant.remove(profile)
    print(movietitle)
    print(description)
    return render(request, 'profileDetail.html', {'profile': profile, 'events': events})


def profileDetail(request):
    profile = Profile.objects.filter(userName=request.user).last()
    if request.method == 'POST':
        messages.success(request, "You have been added to a new event!")
        # need to use .filter for M-to-M relationships
        event = Event.objects.filter(mediaTitle__exact=request.POST["eventName"]).last()
        event.participant.add(profile)
    events = Event.objects.filter(participant=profile)
    print(events.values())
    return render(request, 'profileDetail.html', {'profile': profile, 'events': events})


def generateToken():
    token = jwt.encode({'iss': 'dWC4PepmTZOX2yJldbmbjA', 'exp': time() + 5000}, 'IOe2IfGpjP5WkDCeLaXXH6Fgem8Zz8pnUh8m',
                       algorithm='HS256')
    return token


def createMeeting(startTime, city, username, movieTitle):
    meetingdetails = {"topic": "WatchParty to watch " + movieTitle + " with " + username,
                      "type": 2,
                      "start_time": startTime,
                      "duration": "180",
                      "timezone": "US/" + city,
                      "agenda": "Watching movies / TV shows",

                      "settings": {"host_video": "true",
                                   "participant_video": "true",
                                   "join_before_host": "False",
                                   "mute_upon_entry": "False",
                                   "watermark": "false",
                                   "audio": "voip",
                                   "auto_recording": "none",
                                   "enforce_login": "true",
                                   }
                      }
    headers = {'authorization': 'Bearer ' + generateToken(),
               'content-type': 'application/json'}
    zoomData = requests.post(
        f'https://api.zoom.us/v2/users/me/meetings',
        headers=headers, data=json.dumps(meetingdetails))
    jsonZoomData = json.loads(zoomData.text)
    return jsonZoomData


def settingsDetail(request):
    return render(request, 'profileSettingsDetail.html', {})


def profileSettings(request):
    if request.method == 'POST':
        interests = request.POST["interests"]
        firstFavoriteMovie = request.POST["firstFavoriteMovie"]
        secondFavoriteMovie = request.POST["secondFavoriteMovie"]
        thirdFavoriteMovie = request.POST["thirdFavoriteMovie"]
        fourthFavoriteMovie = request.POST["fourthFavoriteMovie"]
        fifthFavoriteMovie = request.POST["fifthFavoriteMovie"]
        firstFavoriteTVShow = request.POST["firstFavoriteTVShow"]
        secondFavoriteTVShow = request.POST["secondFavoriteTVShow"]
        thirdFavoriteTVShow = request.POST["thirdFavoriteTVShow"]
        fourthFavoriteTVShow = request.POST["fourthFavoriteTVShow"]
        fifthFavoriteTVShow = request.POST["fifthFavoriteTVShow"]
        profile = Profile.objects.filter(userName = request.user)
        profile.update(interests=interests, firstFavoriteMovie=firstFavoriteMovie,
                          secondFavoriteMovie=secondFavoriteMovie,
                          thirdFavoriteMovie=thirdFavoriteMovie, fourthFavoriteMovie=fourthFavoriteMovie,
                          fifthFavoriteMovie=fifthFavoriteMovie, firstFavoriteTVShow=firstFavoriteTVShow,
                          secondFavoriteTVShow=secondFavoriteTVShow, thirdFavoriteTVShow=thirdFavoriteTVShow,
                          fourthFavoriteTVShow=fourthFavoriteTVShow, fifthFavoriteTVShow=fifthFavoriteTVShow)
        return HttpResponseRedirect(reverse('watchingparty:profile'))

    return render(request, 'profileSettingsDetail.html', {})


def planMovie(request):
    if request.method == 'POST':
        title = request.POST["mediaTitle"]
        user = request.user.username
        print(request.scheme)
        time = request.POST["eventDate"]
        describe = request.POST["description"]
        temp = request.POST["platform"]
        address = request.POST["address"]
        city = ""
        curProf = Profile.objects.get(userName__exact=request.user)
        x = Event(mediaTitle=title, username=user,
                  eventDate=time, description=describe,
                  platform=temp, address=address,
                  city=city, creator=curProf)
        x.save()
        print("Am I inside this post request")
        if temp != "movieStock.jpeg":
            zoomData = createMeeting(time, city, user, title)
            join_URL = zoomData["join_url"]
            meetingPassword = zoomData["password"]
            meeting = Meeting(link=join_URL, password=meetingPassword, username=user, movieTitle=title)
            meeting.save()
        return render(request, 'PlanMovie.html', {})
        # return HttpResponse(temp.render(request))
        # return HttpResponseRedirect('index') # goto main page so user sees new addition

    return render(request, 'PlanMovie.html', {})

def movieInfo(request, movietitle, description):
    movie = Event.objects.filter(mediaTitle=movietitle).filter(description=description).last()
    if movie.platform == "movieStock.jpeg":
        locationData = requests.get(
            f"https://api.openrouteservice.org/geocode/search?api_key=5b3ce3597851110001cf62487a5f0088845f4bf7baed2d3f23d802e9&text={movie.address}")
        jsonLocationData = json.loads(locationData.text)
        featuresData = jsonLocationData["features"]
        data = featuresData[0]
        geometryData = data["geometry"]
        coordinates = geometryData["coordinates"]
        finishLongitude = coordinates[0]
        finishLongitudeString = str(finishLongitude)
        finishLatitude = coordinates[1]
        finishLatitudeString = str(finishLatitude)
        # Include this in production
        # ip = request.META.get('REMOTE_ADDR', None)
        g = geocoder.ip('me')
        startLongitude = g.lng
        startLongitudeString = str(startLongitude)
        startLatitude = g.lat
        startLatitudeString = str(startLatitude)
        directionData = requests.get(
            f'https://api.openrouteservice.org/v2/directions/driving-car?api_key=5b3ce3597851110001cf62487a5f0088845f4bf7baed2d3f23d802e9&start={startLongitudeString},{startLatitudeString}&end={finishLongitudeString},{finishLatitudeString}')
        jsonDirectionData = json.loads(directionData.text)
        jsonDirectionData2 = jsonDirectionData["features"]
        jsonDirectionData3 = jsonDirectionData2[0]
        jsonDirectionData4 = jsonDirectionData3["properties"]
        jsonDirectionData5 = jsonDirectionData4["segments"]
        jsonDirectionData6 = jsonDirectionData5[0]
        jsonDirectionData7 = jsonDirectionData6["steps"]
        instructions = []
        for step in jsonDirectionData7:
            instructions.append(step["instruction"])
        return render(request, 'MovieInfo.html',
                      {'event': movie, 'coordinates': coordinates, 'instructions': instructions, })

    else:
        meeting = Meeting.objects.filter(username=movie.username, movieTitle=movie.mediaTitle).last()
        zoomLink = meeting.link
        zoomPassword = meeting.password
        return render(request, 'MovieInfo.html',
                      {'event': movie, 'link': zoomLink, 'password': zoomPassword, })
class SearchView(TemplateView):
        template_name = 'search.html'

class SearchResultsView(ListView):
    model = Event
    template_name = 'searchResults.html'

    def get_queryset(self):
        query = self.request.GET.get("q")
        object_list = Event.objects.filter(
            Q(mediaTitle__icontains=query) | Q(username__contains=query)
        )
        return object_list

templates/watchingparty/PlanMovie.html
{% extends "base.html" %}
{% block content %}
<!--
REFERENCES
Title: <Javascript component>
Author: <Trevor Eyre>
URL: <https://autocomplete.trevoreyre.com/#/javascript-component?id=styling-and-customization>
 -->
<form action="{% url 'watchingparty:planMovie' %}" method="post" class="mx-auto col-auto" style="height:100%;">
{% csrf_token %}
<div style = "margin-top:5%; width: 70%;" class="mx-auto">
    <h2>Create a new event!</h2>
    <div class="mb-3 col-auto">
        <label for="mediaTitle" class="form-label">What you're watching:</label>
        <input type="text" id="mediaTitle" name="mediaTitle" class="form-control" required>
    </div>
    <div class="mb-3 form-group">
    <label for="exampleFormControlSelect1">Select your Platform: </label>
    <select class="form-select" name="platform" id="exampleFormControlSelect1" required>
      <option value="disneyplus.jpg">Disney Plus</option>
      <option value="hbo-max.png">HBO Max</option>
      <option value="hulu.jpeg">Hulu</option>
      <option value="netflix.jpeg">Netflix</option>
      <option value="prime.jpeg">Amazon Prime</option>
      <option value="movieStock.jpeg">Theater/Other (In-Person)</option>
    </select>
  </div>
    <div class="mb-3 col-auto">
       <label for="eventDate" class="form-label">Event Date:</label>
        <input type="date" id="eventDate" name="eventDate" class="form-control" required>
    </div>
    <div class="mb-3 col-auto">
        <label for="description" class="form-label">Description:</label>
        <textarea id="description" name="description" class="form-control" required></textarea>
    </div>
    <div class="mb-3 col-auto">
        <label for="address" class="form-label">Movie Theater Address (In the Format: House Number Street Name, City, State) (If Online: Type N/A into the box):</label>
        <div id="autocomplete" class="autocomplete">
            <input class="autocomplete-input"  id="address" name="address" placeholder="Search for an address" aria-label="Search for an address">
            <ul class="autocomplete-result-list"></ul>
        </div>
    </div>
    <div class="mb-3 col-auto">
  <button type="submit" class="btn btn-primary">Create Event</button>
</div>
</div>
</form>
<link
  rel="stylesheet"
  href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"
/>
  <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>

        <script>
            new Autocomplete('#autocomplete', {
            search: input => {
            const url = `https://api.geoapify.com/v1/geocode/autocomplete?text=${input}&apiKey=
7c602e0cd2f54cba9b2c5c5897561a91`
            return new Promise(resolve =>{
                fetch(url)
                .then(response => response.json())
                .then(data => {
                    const arr = [];
                    Array.from(data.features).forEach(feature => {
                        arr.push(feature.properties.formatted)
                    })
                    resolve(arr)
                })
            })
            }
        })
        </script>
{% endblock %}

templates/watchingparty/base.html
<!--
REFERENCES
Title: <Django Google Authentication using django-allauth>
Author: <Muhd Rahiman>
Date: <October 28th, 2021>
Code version: <Python 3>
URL: <https://dev.to/mdrhmn/django-google-authentication-using-django-allauth-18f8>
 -->
{% load socialaccount %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'watchingparty/style.css' %}">
<!DOCTYPE html>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Sets Background Color and adjusts height for website -->
  <!-- Navigation Bar for Homepage -->
<div class="background container-fluid" style="height: 100vh; overflow: auto; background: #355C7D; background: -webkit-linear-gradient(to right, #C06C84, #6C5B7B, #355C7D); background: linear-gradient(to right, #C06C84, #6C5B7B, #355C7D);">
  <nav class="navbar navbar-expand-lg navbar-light bg-light" style="border-radius: 10px;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'watchingparty:index' %}">Watch Party</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'watchingparty:index' %}">Home </a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'watchingparty:planMovie' %}"> Plan a Movie Night </a>
              {% endif %}
          </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'watchingparty:search' %}"> Search Events </a>
                 {% endif %}
          </li>
        </ul>
        <!-- User Sign-in and Profile -->
          <a class="d-flex">
          {% if user.is_authenticated %}
            <ul class="nav navbar-nav ms-auto">
                <li class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><img class="circular_img" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" /></a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a href="{% url 'watchingparty:profile' %}" class="dropdown-item">Profile</a>
                        <a href="{% url 'watchingparty:settings' %}" class="dropdown-item">Profile Settings</a>
                        <div class="dropdown-divider"></div>
                        <a href="{% url 'watchingparty:logout' %}" class="dropdown-item">Logout</a>
                    </div>
                </li>
            </ul>
          {% else %}
          <a href="{% provider_login_url 'google' action='reauthenticate' %}">Login with Google</a>
          {% endif %}
        </a>
      </div>
    </div>
  </nav>
    <head>
        {% block header %}
        {% endblock %}
    </head>
    <body style= "height: 100vh; width: 100vw;">
        {% block content %}
        {% endblock %}
    </body>
</div>

templates/watchingparty/profileDetail.html
{% extends "base.html" %}
{% block content %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages|slice:":1" %}
                {#    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>#}
                <script type="text/javascript">
                    alert("{{message}}");
                </script>
            {% endfor %}
        </ul>

    {% endif %}

    <div class="container-fluid justify-content-center text-center">

        <img class="big_circular_img" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" alt="profile pic"/>

        <h2 class="username_text"><u> {{ user.username }} </u></h2>
    <h4 class="mx-auto" style="margin-top: 3%;">Your Upcoming Events:</h4>
        {% if events %}
            <div class="list-group mx-auto" style="width: 30%; margin-bottom: 3%;">
           {% for event in events %}
                <a href="#" class="list-group-item list-group-item-action" aria-current="true">
                    <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">{{ event.mediaTitle }}</h5>
                        <small> {{ event.eventDate }}</small>
                    </div>
                    <p class="mb-1"> {{ event.description }}</p>
                    <small>{{ event.username }}</small>
                                <a href="/../delete/{{ event.mediaTitle }}/{{ event.description }}" class="btn btn-danger">Delete</a>

                </a>
            {% endfor %}
            </div>
        {% endif %}


        <p class="profile_text"> Interested in:</p>
        <p class="line_text" style="border-style: solid;">{{ profile.interests }} </p>
        <ul class="profile_text" style="list-style-position: inside; border-style: solid;"> Top 5 Favorite Movies:
            <li class="line_text"> 1. {{ profile.firstFavoriteMovie }}</li>
            <li class="line_text"> 2. {{ profile.secondFavoriteMovie }}</li>
            <li class="line_text"> 3. {{ profile.thirdFavoriteMovie }}</li>
            <li class="line_text"> 4. {{ profile.fourthFavoriteMovie }}</li>
            <li class="line_text"> 5. {{ profile.fifthFavoriteMovie }}</li>
        </ul>
        <ul class="profile_text" style="list-style-position: inside; border-style: solid;"> Top 5 Favorite Shows:
            <li class="line_text"> 1. {{ profile.firstFavoriteTVShow }}</li>
            <li class="line_text"> 2. {{ profile.secondFavoriteTVShow }}</li>
            <li class="line_text"> 3. {{ profile.thirdFavoriteTVShow }}</li>
            <li class="line_text"> 4. {{ profile.fourthFavoriteTVShow }}</li>
            <li class="line_text"> 5. {{ profile.fifthFavoriteTVShow }}</li>
        </ul>
        <button type="submit" class="btn btn-primary"><a style="all:unset" href="{% url 'watchingparty:settings' %}">Edit
            Profile?</a></button>
    </div>
{% endblock %}

templates/watchingparty/profileSettingsDetail.html
{% extends "base.html" %}
{% block header %}

<!-- Header of Profile Settings -->
<div class="container-fluid justify-content-center text-center">
<img class="big_circular_img" src="{{ user.socialaccount_set.all.0.get_avatar_url }}" />
<h2 class="username_text"> <u> {{user.username}}'s Settings </u> </h2>
{% endblock %}

<!-- Body of Profile Settings -->
{% block content %}
    <form action="{% url 'watchingparty:save' %}" name="settingsText" method="post" class="mx-auto col-auto">
     {% csrf_token %}
        <p class="profile_text"> Interested in:</p>
        <textarea id="settingsText" name="interests" class="text" cols="120" rows="6" placeholder="Adventure, Thrillers, Sports, etc." required></textarea>
         <ul class="profile_text" style ="list-style-position: inside;"> Top 5 Favorite Movies:
     <div class="mb-3 col-auto">
        <label for="firstFavoriteMovie" class="form-label">1.</label>
        <input type="text" id="firstFavoriteMovie" name="firstFavoriteMovie" placeholder="Movie 1" required>
    </div>
      <div class="mb-3 col-auto">
        <label for="secondFavoriteMovie" class="form-label">2.</label>
        <input type="text" id="secondFavoriteMovie" name="secondFavoriteMovie" placeholder="Movie 2" required>
    </div>
     <div class="mb-3 col-auto">
        <label for="thirdFavoriteMovie" class="form-label">3.</label>
        <input type="text" id="thirdFavoriteMovie" name="thirdFavoriteMovie" placeholder="Movie 3" required>
    </div>
     <div class="mb-3 col-auto">
        <label for="fourthFavoriteMovie" class="form-label">4.</label>
        <input type="text" id="fourthFavoriteMovie" name="fourthFavoriteMovie" placeholder="Movie 4" required>
    </div>
     <div class="mb-3 col-auto">
        <label for="fifthFavoriteMovie" class="form-label">5.</label>
        <input type="text" id="fifthFavoriteMovie" name="fifthFavoriteMovie" placeholder="Movie 5" required>
    </div>
              </ul>
     <ul class="profile_text" style ="list-style-position: inside;"> Top 5 Favorite TV Shows:
        <div class="mb-3 col-auto">
            <label for="firstFavoriteTVShow" class="form-label">1.</label>
            <input type="text" id="firstFavoriteTVShow" name="firstFavoriteTVShow" placeholder="Show 1" required>
        </div>
          <div class="mb-3 col-auto">
            <label for="secondFavoriteTVShow" class="form-label">2.</label>
            <input type="text" id="secondFavoriteTVShow" name="secondFavoriteTVShow" placeholder="Show 2" required>
        </div>
         <div class="mb-3 col-auto">
            <label for="thirdFavoriteTVShow" class="form-label">3.</label>
            <input type="text" id="thirdFavoriteTVShow" name="thirdFavoriteTVShow" placeholder="Show 3" required>
        </div>
         <div class="mb-3 col-auto">
            <label for="fourthFavoriteTVShow" class="form-label">4.</label>
            <input type="text" id="fourthFavoriteTVShow" name="fourthFavoriteTVShow" placeholder="Show 4" required>
        </div>
         <div class="mb-3 col-auto">
            <label for="fifthFavoriteTVShow" class="form-label">5.</label>
            <input type="text" id="fifthFavoriteTVShow" name="fifthFavoriteTVShow" placeholder="Show 5" required>
        </div>
         </ul>
        <button type="submit" value="profileDetail" class="btn btn-primary">Save Changes?</button>
 </form>
</div>
{% endblock %}

templates/watchingparty/search.html
{% extends "base.html" %}

{% load static %}
{% csrf_token %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search</title>
</head>

{% block content %}
<body>
<h1>Search Events</h1>

<form action="{% url 'watchingparty:searchResults' %}" method="get">
    <div class="mb-3 col-auto">
        <label>Search a media title or username:</label>
        <input name="q" type="text" placeholder="Search..." class="form-control" required>
    </div>
</form>
</body>
{% endblock %}
</html>

templates/watchingparty/searchResults.html
{% extends "base.html" %}

{% load static %}
{% csrf_token %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Search Results</title>
</head>
{% block content %}
<body>
<h1>Search Results</h1>

<ul>
    <div class="row">
        {% for card in object_list %}
            <div class="col-sm-3 mb-3">
                <div class="card" style="width: 18rem;">
                    <img src="../../static/watchingparty/images/{{card.platform}}" onerror="../../static/watchingparty/images/movieStock.jpeg" width="50" height="300"
                         class="card-img-top">

                    <div class="card-body text-center">
                        <h5 class="card-title">{{ card.mediaTitle }}</h5>
                        <p><u> Username:</u> {{ card.username }}</p>
                        <p><u> Date & Time:</u> {{ card.eventDate }} </p>
                        <p class="card-text"> {{ card.description }}</p>
                        <p><u> Attendees:</u>
                            {% if card.participant.all.count == 0 %}
                            No Attendees Yet!
                              {% endif %}
                              {% for person in card.participant.all %}
                              {% if forloop.last %}
                              {{person.userName}}
                              {% else %}
                              {{person.userName}},
                              {% endif %}
                              {% endfor %}
                        </p>
                        <form action="profile/" method="post"> {% csrf_token %}
                            <input type="hidden" value="{{ card.mediaTitle }}" name="eventName">
                        <button type="submit" class="btn btn-primary"> Watch with me!</button>
                        </form>
                        <a href="/{{card.mediaTitle}}/{{card.description}}" class="btn btn-primary" style="margin-top: 5px;">More Information!</a>
                    </div>

                </div>
            </div>
        {% endfor %}

    </div>
</ul>
</body>
{% endblock %}
</html>